#
# Header with path definitions for entire project.
#
# Automatically generated by Waf, do not change!
#
# If paths need adjustment, perform those in the root wscript file.
#


PATH_BLD <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research'
PATH_IN_DATA <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/src/original_data'
PATH_IN_MODEL_CODE <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/src/model_code'
PATH_IN_MODEL_SPECS <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/src/model_specs'
PATH_LIBRARY <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/src/library'
PATH_OUT_ANALYSIS <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/out/analysis'
PATH_OUT_DATA <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/out/data'
PATH_OUT_FIGURES <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/out/figures'
PATH_OUT_FINAL <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/out/final'
PATH_OUT_MODEL_SPECS <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/src/model_specs'
PATH_OUT_TABLES <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research/bld/out/tables'
PATH_PROJECT_ROOT <<- '/Users/anastasiiagordienko/Desktop/DST/dst_research'
